[stdlog] 2022-10-28 21:03:21,192 avocado.test INFO | INIT 1-tests/system_base/util-linux/tc_ag_util-linux_partx_fun_002.py:Test.test
[stdlog] 2022-10-28 21:03:21,193 avocado.test DEBUG| PARAMS (key=timeout, path=*, default=None) => None
[stdlog] 2022-10-28 21:03:21,193 avocado.test DEBUG| Test metadata:
[stdlog] 2022-10-28 21:03:21,193 avocado.test DEBUG|   filename: /root/GitRepo/anolis-pkg-tests/tests/system_base/util-linux/tc_ag_util-linux_partx_fun_002.py
[stdlog] 2022-10-28 21:03:21,193 avocado.test DEBUG|   teststmpdir: /var/tmp/avocado_cmoau920
[stdlog] 2022-10-28 21:03:21,194 avocado.test INFO | START 1-tests/system_base/util-linux/tc_ag_util-linux_partx_fun_002.py:Test.test
[stdlog] 2022-10-28 21:03:21,194 avocado.test INFO | setup
[stdlog] 2022-10-28 21:03:21,194 avocado.test DEBUG| PARAMS (key=remote, path=*, default=None) => None
[stdlog] 2022-10-28 21:03:21,194 avocado.utils.process INFO | Running 'rpm -q util-linux'
[stdlog] 2022-10-28 21:03:21,203 avocado.utils.process DEBUG| [stdout] util-linux-2.32.1-35.0.1.an8.x86_64
[stdlog] 2022-10-28 21:03:21,204 avocado.utils.process INFO | Command 'rpm -q util-linux' finished with 0 after 0.008611063s
[stdlog] 2022-10-28 21:03:21,204 avocado.utils.process INFO | Running 'yum update util-linux -y'
[stdlog] 2022-10-28 21:03:21,496 avocado.utils.process DEBUG| [stdout] Last metadata expiration check: 2:45:49 ago on Fri 28 Oct 2022 06:17:32 PM CST.
[stdlog] 2022-10-28 21:03:21,763 avocado.utils.process DEBUG| [stdout] Dependencies resolved.
[stdlog] 2022-10-28 21:03:21,764 avocado.utils.process DEBUG| [stdout] Nothing to do.
[stdlog] 2022-10-28 21:03:21,765 avocado.utils.process DEBUG| [stdout] Complete!
[stdlog] 2022-10-28 21:03:22,059 avocado.utils.process INFO | Command 'yum update util-linux -y' finished with 0 after 0.854891359s
[stdlog] 2022-10-28 21:03:22,060 avocado.utils.process INFO | Running 'sudo partx --add --verbose {{path/to/device_or_disk_image}}'
[stdlog] 2022-10-28 21:03:22,070 avocado.utils.process DEBUG| [stderr] partx: 
[stdlog] 2022-10-28 21:03:22,071 avocado.utils.process DEBUG| [stderr] stat of {{path/to/device_or_disk_image}} failed
[stdlog] 2022-10-28 21:03:22,071 avocado.utils.process DEBUG| [stderr] : 
[stdlog] 2022-10-28 21:03:22,071 avocado.utils.process DEBUG| [stderr] No such file or directory
[stdlog] 2022-10-28 21:03:22,072 avocado.utils.process INFO | Command 'sudo partx --add --verbose {{path/to/device_or_disk_image}}' finished with 1 after 0.011296419s
[stdlog] 2022-10-28 21:03:22,072 avocado.test ERROR| 
[stdlog] 2022-10-28 21:03:22,073 avocado.test ERROR| Reproduced traceback from: /usr/local/lib/python3.6/site-packages/avocado/core/test.py:761
[stdlog] 2022-10-28 21:03:22,073 avocado.test ERROR| Traceback (most recent call last):
[stdlog] 2022-10-28 21:03:22,073 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/system_base/util-linux/tc_ag_util-linux_partx_fun_002.py", line 27, in test
[stdlog] 2022-10-28 21:03:22,073 avocado.test ERROR|     ret_c, ret_o = self.cmd("sudo partx --add --verbose {{path/to/device_or_disk_image}}")
[stdlog] 2022-10-28 21:03:22,073 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/common/basetest.py", line 54, in cmd
[stdlog] 2022-10-28 21:03:22,073 avocado.test ERROR|     return self.local.cmd(command, ignore_status=ignore_status)
[stdlog] 2022-10-28 21:03:22,073 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/common/hosts.py", line 45, in cmd
[stdlog] 2022-10-28 21:03:22,073 avocado.test ERROR|     result = process.run(command, ignore_status=ignore_status, shell=True)
[stdlog] 2022-10-28 21:03:22,073 avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1015, in run
[stdlog] 2022-10-28 21:03:22,073 avocado.test ERROR|     raise CmdError(cmd, sp.result)
[stdlog] 2022-10-28 21:03:22,073 avocado.test ERROR| avocado.utils.process.CmdError: Command 'sudo partx --add --verbose {{path/to/device_or_disk_image}}' failed.
[stdlog] 2022-10-28 21:03:22,073 avocado.test ERROR| stdout: b''
[stdlog] 2022-10-28 21:03:22,073 avocado.test ERROR| stderr: b'partx: stat of {{path/to/device_or_disk_image}} failed: No such file or directory\n'
[stdlog] 2022-10-28 21:03:22,074 avocado.test ERROR| additional_info: None
[stdlog] 2022-10-28 21:03:22,074 avocado.test ERROR| 
[stdlog] 2022-10-28 21:03:22,074 avocado.test DEBUG| Local variables:
[stdlog] 2022-10-28 21:03:22,086 avocado.test DEBUG|  -> self <class 'tc_ag_util-linux_partx_fun_002.Test'>: 1-tests/system_base/util-linux/tc_ag_util-linux_partx_fun_002.py:Test.test
[stdlog] 2022-10-28 21:03:22,086 avocado.test INFO | teardown
[stdlog] 2022-10-28 21:03:22,086 avocado.utils.process INFO | Running 'yum erase  -y'
[stdlog] 2022-10-28 21:03:22,369 avocado.utils.process DEBUG| [stderr] No packages marked for removal.
[stdlog] 2022-10-28 21:03:22,377 avocado.utils.process DEBUG| [stdout] Dependencies resolved.
[stdlog] 2022-10-28 21:03:22,378 avocado.utils.process DEBUG| [stdout] Nothing to do.
[stdlog] 2022-10-28 21:03:22,378 avocado.utils.process DEBUG| [stdout] Complete!
[stdlog] 2022-10-28 21:03:22,677 avocado.utils.process INFO | Command 'yum erase  -y' finished with 0 after 0.589836177s
[stdlog] 2022-10-28 21:03:22,677 avocado.test ERROR| Traceback (most recent call last):
[stdlog] 2022-10-28 21:03:22,677 avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 796, in _run_avocado
[stdlog]     raise test_exception
[stdlog] 2022-10-28 21:03:22,677 avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/core/test.py", line 756, in _run_avocado
[stdlog]     testMethod()
[stdlog] 2022-10-28 21:03:22,677 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/system_base/util-linux/tc_ag_util-linux_partx_fun_002.py", line 27, in test
[stdlog]     ret_c, ret_o = self.cmd("sudo partx --add --verbose {{path/to/device_or_disk_image}}")
[stdlog] 2022-10-28 21:03:22,677 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/common/basetest.py", line 54, in cmd
[stdlog]     return self.local.cmd(command, ignore_status=ignore_status)
[stdlog] 2022-10-28 21:03:22,677 avocado.test ERROR|   File "/root/GitRepo/anolis-pkg-tests/tests/common/hosts.py", line 45, in cmd
[stdlog]     result = process.run(command, ignore_status=ignore_status, shell=True)
[stdlog] 2022-10-28 21:03:22,677 avocado.test ERROR|   File "/usr/local/lib/python3.6/site-packages/avocado/utils/process.py", line 1015, in run
[stdlog]     raise CmdError(cmd, sp.result)
[stdlog] 2022-10-28 21:03:22,677 avocado.test ERROR| avocado.utils.process.CmdError: Command 'sudo partx --add --verbose {{path/to/device_or_disk_image}}' failed.
[stdlog] stdout: b''
[stdlog] stderr: b'partx: stat of {{path/to/device_or_disk_image}} failed: No such file or directory\n'
[stdlog] additional_info: None
[stdlog] 2022-10-28 21:03:22,677 avocado.test ERROR| ERROR 1-tests/system_base/util-linux/tc_ag_util-linux_partx_fun_002.py:Test.test -> CmdError: Command 'sudo partx --add --verbose {{path/to/device_or_disk_image}}' failed.
[stdlog] stdout: b''
[stdlog] stderr: b'partx: stat of {{path/to/device_or_disk_image}} failed: No such file or directory\n'
[stdlog] additional_info: None
[stdlog] 2022-10-28 21:03:22,678 avocado.test INFO | 
