+ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n '' ']'
+ trap POST_TEST_DEFAULT EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n '' ']'
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Dec 23 03:02:32 2022 - INFO  - Start to run test.
+ service auditd restart
oe_test_audit_count_number_of_event.sh: line 25: service: command not found
+ CHECK_RESULT 127 0 0 'start failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='start failed'
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'start failed'
+ LOG_ERROR 'start failed'
+ message='start failed'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'start failed'
Fri Dec 23 03:02:32 2022 - ERROR - start failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_count_number_of_event.sh line 26'
+ message='oe_test_audit_count_number_of_event.sh line 26'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_count_number_of_event.sh line 26'
Fri Dec 23 03:02:33 2022 - ERROR - oe_test_audit_count_number_of_event.sh line 26
+ return 0
+ aureport -e -i --summary
+ grep 'Event Summary Report'
Fri Dec 23 03:32:29 2022 - ERROR - Timeout : Command 'bash -x oe_test_audit_count_number_of_event.sh' timed out after 1799.996757904999 seconds
