+ source ./common/disk_lib.sh
++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment!'
+ message='Start to prepare the test environment!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment!'
Thu Dec 22 20:41:18 2022 - INFO  - Start to prepare the test environment!
+ DNF_INSTALL lvm2
+ pkgs=lvm2
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs lvm2 --node 1 --tempfile ''
Thu Dec 22 20:41:34 2022 - INFO  - pkgs:(lvm2) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/GitRepo/mugen-riscv/libs/locallibs/get_test_device.py --device disk --node 1
+ disks=
+ disk_list=($disks)
+ local_disk=
+ local_disk1=
+ local_disk2=
+ local_disk3=
+ LOG_INFO 'End to prepare the test environment!'
+ message='End to prepare the test environment!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment!'
Thu Dec 22 20:41:44 2022 - INFO  - End to prepare the test environment!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Thu Dec 22 20:41:45 2022 - INFO  - Start executing testcase!
+ pvcreate -y /dev/ /dev/
  No device found for /dev/.
  No device found for /dev/.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_002.sh line 30'
+ message='oe_test_lvm2_pvmove_002.sh line 30'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_002.sh line 30'
Thu Dec 22 20:41:47 2022 - ERROR - oe_test_lvm2_pvmove_002.sh line 30
+ return 0
+ pvs
+ grep /dev/
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_002.sh line 32'
+ message='oe_test_lvm2_pvmove_002.sh line 32'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_002.sh line 32'
Thu Dec 22 20:41:48 2022 - ERROR - oe_test_lvm2_pvmove_002.sh line 32
+ return 0
+ vgcreate test /dev/ /dev/
  No device found for /dev/.
  No device found for /dev/.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_002.sh line 34'
+ message='oe_test_lvm2_pvmove_002.sh line 34'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_002.sh line 34'
Thu Dec 22 20:41:49 2022 - ERROR - oe_test_lvm2_pvmove_002.sh line 34
+ return 0
+ lvcreate -L 50MB -n lv1 test
+ grep 'Logical volume "lv1" created'
  Volume group "test" not found
  Cannot process volume group test
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_002.sh line 36'
+ message='oe_test_lvm2_pvmove_002.sh line 36'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_002.sh line 36'
Thu Dec 22 20:41:51 2022 - ERROR - oe_test_lvm2_pvmove_002.sh line 36
+ return 0
+ grep 'Moved: 100.00%'
+ pvmove /dev/ /dev/
modprobe: FATAL: Module dm-mirror not found in directory /lib/modules/5.10.0-9.oe2203.riscv64
  /usr/sbin/modprobe failed: 1
  Required device-mapper target(s) not detected in your kernel.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_002.sh line 38'
+ message='oe_test_lvm2_pvmove_002.sh line 38'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_002.sh line 38'
Thu Dec 22 20:41:52 2022 - ERROR - oe_test_lvm2_pvmove_002.sh line 38
+ return 0
+ pvmove -A y /dev/ /dev/
+ grep 'Moved: 100.00%'
modprobe: FATAL: Module dm-mirror not found in directory /lib/modules/5.10.0-9.oe2203.riscv64
  /usr/sbin/modprobe failed: 1
  Required device-mapper target(s) not detected in your kernel.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_002.sh line 40'
+ message='oe_test_lvm2_pvmove_002.sh line 40'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_002.sh line 40'
Thu Dec 22 20:41:53 2022 - ERROR - oe_test_lvm2_pvmove_002.sh line 40
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ grep 'Moved: 100.00%'
+ pvmove -n lv1 /dev/ /dev/
modprobe: FATAL: Module dm-mirror not found in directory /lib/modules/5.10.0-9.oe2203.riscv64
  /usr/sbin/modprobe failed: 1
  Required device-mapper target(s) not detected in your kernel.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_002.sh line 43'
+ message='oe_test_lvm2_pvmove_002.sh line 43'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_002.sh line 43'
Thu Dec 22 20:42:00 2022 - ERROR - oe_test_lvm2_pvmove_002.sh line 43
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ pvmove --alloc contiguous /dev/ /dev/
+ grep 'Moved: 100.00%'
modprobe: FATAL: Module dm-mirror not found in directory /lib/modules/5.10.0-9.oe2203.riscv64
  /usr/sbin/modprobe failed: 1
  Required device-mapper target(s) not detected in your kernel.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_002.sh line 46'
+ message='oe_test_lvm2_pvmove_002.sh line 46'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_002.sh line 46'
Thu Dec 22 20:42:07 2022 - ERROR - oe_test_lvm2_pvmove_002.sh line 46
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ grep 'Moved: 100.00%'
+ pvmove --atomic /dev/ /dev/
modprobe: FATAL: Module dm-mirror not found in directory /lib/modules/5.10.0-9.oe2203.riscv64
  /usr/sbin/modprobe failed: 1
  Required device-mapper target(s) not detected in your kernel.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_002.sh line 49'
+ message='oe_test_lvm2_pvmove_002.sh line 49'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_002.sh line 49'
Thu Dec 22 20:42:15 2022 - ERROR - oe_test_lvm2_pvmove_002.sh line 49
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ grep 'Moved: 100.00%'
+ pvmove --noudevsync /dev/ /dev/
modprobe: FATAL: Module dm-mirror not found in directory /lib/modules/5.10.0-9.oe2203.riscv64
  /usr/sbin/modprobe failed: 1
  Required device-mapper target(s) not detected in your kernel.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_002.sh line 52'
+ message='oe_test_lvm2_pvmove_002.sh line 52'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_002.sh line 52'
Thu Dec 22 20:42:22 2022 - ERROR - oe_test_lvm2_pvmove_002.sh line 52
+ return 0
+ pvmove --noudevsync --reportformat json /dev/ /dev/
+ grep 'Moved: 100.00%'
modprobe: FATAL: Module dm-mirror not found in directory /lib/modules/5.10.0-9.oe2203.riscv64
  /usr/sbin/modprobe failed: 1
  Required device-mapper target(s) not detected in your kernel.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_002.sh line 54'
+ message='oe_test_lvm2_pvmove_002.sh line 54'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_002.sh line 54'
Thu Dec 22 20:42:23 2022 - ERROR - oe_test_lvm2_pvmove_002.sh line 54
+ return 0
+ pvmove --version
+ grep 'LVM version'
  LVM version:     2.03.14(2) (2021-10-20)
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pvmove -h
+ grep 'pvmove PV'
  pvmove PV
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pvmove -v
+ grep 'Checking progress before waiting every 15 seconds'
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvmove_002.sh line 60'
+ message='oe_test_lvm2_pvmove_002.sh line 60'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvmove_002.sh line 60'
Thu Dec 22 20:42:25 2022 - ERROR - oe_test_lvm2_pvmove_002.sh line 60
+ return 0
+ LOG_INFO 'End executing testcase!'
+ message='End executing testcase!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End executing testcase!'
Thu Dec 22 20:42:26 2022 - INFO  - End executing testcase!
+ CASE_RESULT 0
+ case_re=0
+ test -z 12
+ test 12 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Dec 22 20:42:27 2022 - ERROR - failed to execute the case.
+ exit 12
+ post_test
+ LOG_INFO 'Start environment cleanup.'
+ message='Start environment cleanup.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environment cleanup.'
Thu Dec 22 20:42:28 2022 - INFO  - Start environment cleanup.
+ vgremove -f test
  Volume group "test" not found
  Cannot process volume group test
+ pvremove -f /dev/
  No device found for /dev/.
+ pvremove -f /dev/
  No device found for /dev/.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Thu Dec 22 20:42:30 2022 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Thu Dec 22 20:42:31 2022 - INFO  - Finish environment cleanup.
