+ source ./common/disk_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment!'
+ message='Start to prepare the test environment!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment!'
Wed Dec  7 08:46:23 2022 - INFO  - Start to prepare the test environment!
+ DNF_INSTALL lvm2
+ pkgs=lvm2
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs lvm2 --node 1 --tempfile ''
Wed Dec  7 08:46:31 2022 - INFO  - pkgs:(lvm2) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen-riscv/libs/locallibs/get_test_device.py --device disk --node 1
+ disks=
+ disk_list=($disks)
+ local_disk=
+ local_disk1=
+ local_disk2=
+ local_disk3=
+ LOG_INFO 'End to prepare the test environment!'
+ message='End to prepare the test environment!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment!'
Wed Dec  7 08:46:37 2022 - INFO  - End to prepare the test environment!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Wed Dec  7 08:46:38 2022 - INFO  - Start executing testcase!
+ pvcreate -y /dev/
  No device found for /dev/.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvdisplay_001.sh line 30'
+ message='oe_test_lvm2_pvdisplay_001.sh line 30'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvdisplay_001.sh line 30'
Wed Dec  7 08:46:39 2022 - ERROR - oe_test_lvm2_pvdisplay_001.sh line 30
+ return 0
+ pvs
+ grep /dev/
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvdisplay_001.sh line 32'
+ message='oe_test_lvm2_pvdisplay_001.sh line 32'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvdisplay_001.sh line 32'
Wed Dec  7 08:46:40 2022 - ERROR - oe_test_lvm2_pvdisplay_001.sh line 32
+ return 0
+ pvdisplay
+ grep 'PV Name'
+ grep ''
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvdisplay_001.sh line 34'
+ message='oe_test_lvm2_pvdisplay_001.sh line 34'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvdisplay_001.sh line 34'
Wed Dec  7 08:46:40 2022 - ERROR - oe_test_lvm2_pvdisplay_001.sh line 34
+ return 0
+ pvdisplay -c
+ grep '"/dev/" is a new physical volume'
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvdisplay_001.sh line 36'
+ message='oe_test_lvm2_pvdisplay_001.sh line 36'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvdisplay_001.sh line 36'
Wed Dec  7 08:46:41 2022 - ERROR - oe_test_lvm2_pvdisplay_001.sh line 36
+ return 0
+ pvdisplay -m
+ grep 'PV Name'
+ grep ''
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvdisplay_001.sh line 38'
+ message='oe_test_lvm2_pvdisplay_001.sh line 38'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvdisplay_001.sh line 38'
Wed Dec  7 08:46:42 2022 - ERROR - oe_test_lvm2_pvdisplay_001.sh line 38
+ return 0
+ pvdisplay -s
+ grep 'Device "/dev/" has a capacity'
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvdisplay_001.sh line 40'
+ message='oe_test_lvm2_pvdisplay_001.sh line 40'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvdisplay_001.sh line 40'
Wed Dec  7 08:46:43 2022 - ERROR - oe_test_lvm2_pvdisplay_001.sh line 40
+ return 0
+ pvdisplay -C -a
+ grep /dev/
  /dev/vda1         ---     0     0 
  /dev/vda2         ---     0     0 
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ pvdisplay -C --aligned
+ grep /dev/
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvdisplay_001.sh line 44'
+ message='oe_test_lvm2_pvdisplay_001.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvdisplay_001.sh line 44'
Wed Dec  7 08:46:44 2022 - ERROR - oe_test_lvm2_pvdisplay_001.sh line 44
+ return 0
+ pvdisplay -C --binary
+ grep /dev/
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvdisplay_001.sh line 46'
+ message='oe_test_lvm2_pvdisplay_001.sh line 46'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvdisplay_001.sh line 46'
Wed Dec  7 08:46:45 2022 - ERROR - oe_test_lvm2_pvdisplay_001.sh line 46
+ return 0
+ pvdisplay --configreport log
+ grep 'PV Name'
+ grep ''
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvdisplay_001.sh line 48'
+ message='oe_test_lvm2_pvdisplay_001.sh line 48'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvdisplay_001.sh line 48'
Wed Dec  7 08:46:46 2022 - ERROR - oe_test_lvm2_pvdisplay_001.sh line 48
+ return 0
+ pvdisplay --foreign
+ grep '"/dev/" is a new physical volume'
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvdisplay_001.sh line 50'
+ message='oe_test_lvm2_pvdisplay_001.sh line 50'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvdisplay_001.sh line 50'
Wed Dec  7 08:46:47 2022 - ERROR - oe_test_lvm2_pvdisplay_001.sh line 50
+ return 0
+ pvdisplay --ignorelockingfailure
+ grep '"/dev/" is a new physical volume'
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvdisplay_001.sh line 52'
+ message='oe_test_lvm2_pvdisplay_001.sh line 52'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvdisplay_001.sh line 52'
Wed Dec  7 08:46:48 2022 - ERROR - oe_test_lvm2_pvdisplay_001.sh line 52
+ return 0
+ LOG_INFO 'End executing testcase!'
+ message='End executing testcase!'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End executing testcase!'
Wed Dec  7 08:46:48 2022 - INFO  - End executing testcase!
+ CASE_RESULT 0
+ case_re=0
+ test -z 11
+ test 11 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Dec  7 08:46:49 2022 - ERROR - failed to execute the case.
+ exit 11
+ post_test
+ LOG_INFO 'Start environment cleanup.'
+ message='Start environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environment cleanup.'
Wed Dec  7 08:46:49 2022 - INFO  - Start environment cleanup.
+ pvremove -f /dev/
  No device found for /dev/.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Wed Dec  7 08:46:50 2022 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Wed Dec  7 08:46:51 2022 - INFO  - Finish environment cleanup.
