+ source ./common/disk_lib.sh
++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/GitRepo/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ grep expect
+ rpm -qa
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment!'
+ message='Start to prepare the test environment!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment!'
Thu Dec 22 20:33:11 2022 - INFO  - Start to prepare the test environment!
+ DNF_INSTALL lvm2
+ pkgs=lvm2
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/GitRepo/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs lvm2 --node 1 --tempfile ''
Thu Dec 22 20:33:21 2022 - INFO  - pkgs:(lvm2) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/GitRepo/mugen-riscv/libs/locallibs/get_test_device.py --device disk --node 1
+ disks=
+ disk_list=($disks)
+ local_disk=
+ local_disk1=
+ local_disk2=
+ local_disk3=
+ LOG_INFO 'End to prepare the test environment!'
+ message='End to prepare the test environment!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment!'
Thu Dec 22 20:33:30 2022 - INFO  - End to prepare the test environment!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Thu Dec 22 20:33:31 2022 - INFO  - Start executing testcase!
+ pvcreate -y /dev/
  No device found for /dev/.
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvcreate_001.sh line 30'
+ message='oe_test_lvm2_pvcreate_001.sh line 30'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvcreate_001.sh line 30'
Thu Dec 22 20:33:32 2022 - ERROR - oe_test_lvm2_pvcreate_001.sh line 30
+ return 0
+ grep 'PV UUID'
+ pvdisplay
+ pvcreate -y /dev/ --setphysicalvolumesize 30MB
+ grep 'successfully created'
  No device found for /dev/.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvcreate_001.sh line 33'
+ message='oe_test_lvm2_pvcreate_001.sh line 33'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvcreate_001.sh line 33'
Thu Dec 22 20:33:34 2022 - ERROR - oe_test_lvm2_pvcreate_001.sh line 33
+ return 0
+ sed -n 3p
+ pvs
+ grep 30.00m
+ awk '{print$4}'
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvcreate_001.sh line 35'
+ message='oe_test_lvm2_pvcreate_001.sh line 35'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvcreate_001.sh line 35'
Thu Dec 22 20:33:35 2022 - ERROR - oe_test_lvm2_pvcreate_001.sh line 35
+ return 0
+ grep 'successfully created'
+ pvcreate -y /dev/ --dataalignment 10MB
  No device found for /dev/.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvcreate_001.sh line 37'
+ message='oe_test_lvm2_pvcreate_001.sh line 37'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvcreate_001.sh line 37'
Thu Dec 22 20:33:37 2022 - ERROR - oe_test_lvm2_pvcreate_001.sh line 37
+ return 0
+ pvcreate -y /dev/ --metadataignore y
+ grep 'successfully created'
  No device found for /dev/.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvcreate_001.sh line 39'
+ message='oe_test_lvm2_pvcreate_001.sh line 39'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvcreate_001.sh line 39'
Thu Dec 22 20:33:38 2022 - ERROR - oe_test_lvm2_pvcreate_001.sh line 39
+ return 0
+ pvcreate /dev/ -y --metadatatype lvm2
+ grep 'successfully created'
  No device found for /dev/.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvcreate_001.sh line 41'
+ message='oe_test_lvm2_pvcreate_001.sh line 41'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvcreate_001.sh line 41'
Thu Dec 22 20:33:39 2022 - ERROR - oe_test_lvm2_pvcreate_001.sh line 41
+ return 0
+ pvcreate /dev/ -y --zero y
+ grep 'successfully created'
  No device found for /dev/.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvcreate_001.sh line 43'
+ message='oe_test_lvm2_pvcreate_001.sh line 43'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvcreate_001.sh line 43'
Thu Dec 22 20:33:40 2022 - ERROR - oe_test_lvm2_pvcreate_001.sh line 43
+ return 0
+ pvcreate /dev/ -y --dataalignmentoffset 1MB
+ grep 'successfully created'
  No device found for /dev/.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvcreate_001.sh line 45'
+ message='oe_test_lvm2_pvcreate_001.sh line 45'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvcreate_001.sh line 45'
Thu Dec 22 20:33:42 2022 - ERROR - oe_test_lvm2_pvcreate_001.sh line 45
+ return 0
+ grep 'successfully created'
+ pvcreate /dev/ -y --bootloaderareasize 5MB
  No device found for /dev/.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvcreate_001.sh line 47'
+ message='oe_test_lvm2_pvcreate_001.sh line 47'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvcreate_001.sh line 47'
Thu Dec 22 20:33:43 2022 - ERROR - oe_test_lvm2_pvcreate_001.sh line 47
+ return 0
+ pvcreate /dev/ -y --labelsector 3
+ grep 'successfully created'
  No device found for /dev/.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvcreate_001.sh line 49'
+ message='oe_test_lvm2_pvcreate_001.sh line 49'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvcreate_001.sh line 49'
Thu Dec 22 20:33:44 2022 - ERROR - oe_test_lvm2_pvcreate_001.sh line 49
+ return 0
+ pvcreate /dev/ -y --pvmetadatacopies 1
+ grep 'successfully created'
  No device found for /dev/.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvcreate_001.sh line 51'
+ message='oe_test_lvm2_pvcreate_001.sh line 51'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvcreate_001.sh line 51'
Thu Dec 22 20:33:45 2022 - ERROR - oe_test_lvm2_pvcreate_001.sh line 51
+ return 0
+ pvcreate /dev/ -y --metadatasize 10MB
+ grep 'successfully created'
  No device found for /dev/.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvcreate_001.sh line 53'
+ message='oe_test_lvm2_pvcreate_001.sh line 53'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvcreate_001.sh line 53'
Thu Dec 22 20:33:47 2022 - ERROR - oe_test_lvm2_pvcreate_001.sh line 53
+ return 0
+ grep 'successfully created'
+ pvcreate /dev/ -y --metadataignore y
  No device found for /dev/.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_lvm2_pvcreate_001.sh line 55'
+ message='oe_test_lvm2_pvcreate_001.sh line 55'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_lvm2_pvcreate_001.sh line 55'
Thu Dec 22 20:33:48 2022 - ERROR - oe_test_lvm2_pvcreate_001.sh line 55
+ return 0
+ LOG_INFO 'End executing testcase!'
+ message='End executing testcase!'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End executing testcase!'
Thu Dec 22 20:33:49 2022 - INFO  - End executing testcase!
+ CASE_RESULT 0
+ case_re=0
+ test -z 13
+ test 13 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Dec 22 20:33:50 2022 - ERROR - failed to execute the case.
+ exit 13
+ post_test
+ LOG_INFO 'Start environment cleanup.'
+ message='Start environment cleanup.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start environment cleanup.'
Thu Dec 22 20:33:51 2022 - INFO  - Start environment cleanup.
+ pvremove -f /dev/
  No device found for /dev/.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Thu Dec 22 20:33:52 2022 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/GitRepo/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Thu Dec 22 20:33:53 2022 - INFO  - Finish environment cleanup.
