+ source common/common_lib.sh
++ source /root/mugen-riscv/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen-riscv/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Wed Dec  7 23:52:55 2022 - INFO  - Start to prepare the test environment.
+ get_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen-riscv/libs/locallibs/get_test_device.py --device disk --node 1
+ disks='vdb vdc vdd vde'
+ disk_list=($disks)
+ disk1=vdb
+ disk2=vdc
+ DNF_INSTALL ntfs-3g
+ pkgs=ntfs-3g
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py install --pkgs ntfs-3g --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpdyxhztjz
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpdyxhztjz
+ mkntfs --fast /dev/vdb
common/common_lib.sh: line 28: mkntfs: command not found
+ mkntfs --fast /dev/vdc
common/common_lib.sh: line 29: mkntfs: command not found
+ mkdir -p /mnt/windows
+ LOG_INFO 'Finish preparing the test environment.'
+ message='Finish preparing the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish preparing the test environment.'
Wed Dec  7 23:53:27 2022 - INFO  - Finish preparing the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed Dec  7 23:53:28 2022 - INFO  - Start to run test.
+ lowntfs-3g /dev/vdb /mnt/windows -o locale=1
Invalid locale, encoding to UTF-8
NTFS signature is missing.
Failed to mount '/dev/vdb': Invalid argument
The device '/dev/vdb' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?
+ CHECK_RESULT 12 0 0 'Check lowntfs-3g -o locale failed.'
+ actual_result=12
+ expect_result=0
+ mode=0
+ error_log='Check lowntfs-3g -o locale failed.'
+ '[' -z 12 ']'
+ '[' 0 -eq 0 ']'
+ test 12x '!=' 0x
+ test -n 'Check lowntfs-3g -o locale failed.'
+ LOG_ERROR 'Check lowntfs-3g -o locale failed.'
+ message='Check lowntfs-3g -o locale failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check lowntfs-3g -o locale failed.'
Wed Dec  7 23:53:28 2022 - ERROR - Check lowntfs-3g -o locale failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 32'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 32'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 32'
Wed Dec  7 23:53:29 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 32
+ return 0
+ df -h
+ grep /dev/vdb
+ CHECK_RESULT 1 0 0 'Check disk mount failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check disk mount failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check disk mount failed.'
+ LOG_ERROR 'Check disk mount failed.'
+ message='Check disk mount failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check disk mount failed.'
Wed Dec  7 23:53:30 2022 - ERROR - Check disk mount failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 34'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 34'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 34'
Wed Dec  7 23:53:30 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 34
+ return 0
+ umount /mnt/windows
umount: /mnt/windows: not mounted.
+ lowntfs-3g /dev/vdb /mnt/windows -o recover
NTFS signature is missing.
Failed to mount '/dev/vdb': Invalid argument
The device '/dev/vdb' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?
+ CHECK_RESULT 12 0 0 'Check lowntfs-3g -o recover failed.'
+ actual_result=12
+ expect_result=0
+ mode=0
+ error_log='Check lowntfs-3g -o recover failed.'
+ '[' -z 12 ']'
+ '[' 0 -eq 0 ']'
+ test 12x '!=' 0x
+ test -n 'Check lowntfs-3g -o recover failed.'
+ LOG_ERROR 'Check lowntfs-3g -o recover failed.'
+ message='Check lowntfs-3g -o recover failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check lowntfs-3g -o recover failed.'
Wed Dec  7 23:53:31 2022 - ERROR - Check lowntfs-3g -o recover failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 37'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 37'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 37'
Wed Dec  7 23:53:31 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 37
+ return 0
+ df -h
+ grep /dev/vdb
+ CHECK_RESULT 1 0 0 'Check disk mount failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check disk mount failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check disk mount failed.'
+ LOG_ERROR 'Check disk mount failed.'
+ message='Check disk mount failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check disk mount failed.'
Wed Dec  7 23:53:32 2022 - ERROR - Check disk mount failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 39'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 39'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 39'
Wed Dec  7 23:53:32 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 39
+ return 0
+ umount /mnt/windows
umount: /mnt/windows: not mounted.
+ lowntfs-3g /dev/vdb /mnt/windows -o norecover
NTFS signature is missing.
Failed to mount '/dev/vdb': Invalid argument
The device '/dev/vdb' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?
+ CHECK_RESULT 12 0 0 'Check lowntfs-3g -o norecover failed.'
+ actual_result=12
+ expect_result=0
+ mode=0
+ error_log='Check lowntfs-3g -o norecover failed.'
+ '[' -z 12 ']'
+ '[' 0 -eq 0 ']'
+ test 12x '!=' 0x
+ test -n 'Check lowntfs-3g -o norecover failed.'
+ LOG_ERROR 'Check lowntfs-3g -o norecover failed.'
+ message='Check lowntfs-3g -o norecover failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check lowntfs-3g -o norecover failed.'
Wed Dec  7 23:53:33 2022 - ERROR - Check lowntfs-3g -o norecover failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 42'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 42'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 42'
Wed Dec  7 23:53:34 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 42
+ return 0
+ df -h
+ grep /dev/vdb
+ CHECK_RESULT 1 0 0 'Check disk mount failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check disk mount failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check disk mount failed.'
+ LOG_ERROR 'Check disk mount failed.'
+ message='Check disk mount failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check disk mount failed.'
Wed Dec  7 23:53:34 2022 - ERROR - Check disk mount failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 44'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 44'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 44'
Wed Dec  7 23:53:35 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 44
+ return 0
+ umount /mnt/windows
umount: /mnt/windows: not mounted.
+ lowntfs-3g /dev/vdb /mnt/windows -o emove_hiberfile
NTFS signature is missing.
Failed to mount '/dev/vdb': Invalid argument
The device '/dev/vdb' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?
+ CHECK_RESULT 12 0 0 'Check lowntfs-3g -o emove_hiberfile failed.'
+ actual_result=12
+ expect_result=0
+ mode=0
+ error_log='Check lowntfs-3g -o emove_hiberfile failed.'
+ '[' -z 12 ']'
+ '[' 0 -eq 0 ']'
+ test 12x '!=' 0x
+ test -n 'Check lowntfs-3g -o emove_hiberfile failed.'
+ LOG_ERROR 'Check lowntfs-3g -o emove_hiberfile failed.'
+ message='Check lowntfs-3g -o emove_hiberfile failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check lowntfs-3g -o emove_hiberfile failed.'
Wed Dec  7 23:53:35 2022 - ERROR - Check lowntfs-3g -o emove_hiberfile failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 47'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 47'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 47'
Wed Dec  7 23:53:36 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 47
+ return 0
+ df -h
+ grep /dev/vdb
+ CHECK_RESULT 1 0 0 'Check disk mount failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check disk mount failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check disk mount failed.'
+ LOG_ERROR 'Check disk mount failed.'
+ message='Check disk mount failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check disk mount failed.'
Wed Dec  7 23:53:36 2022 - ERROR - Check disk mount failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 49'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 49'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 49'
Wed Dec  7 23:53:37 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 49
+ return 0
+ umount /mnt/windows
umount: /mnt/windows: not mounted.
+ lowntfs-3g /dev/vdb /mnt/windows -o atime
NTFS signature is missing.
Failed to mount '/dev/vdb': Invalid argument
The device '/dev/vdb' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?
+ CHECK_RESULT 12 0 0 'Check lowntfs-3g -o atime failed.'
+ actual_result=12
+ expect_result=0
+ mode=0
+ error_log='Check lowntfs-3g -o atime failed.'
+ '[' -z 12 ']'
+ '[' 0 -eq 0 ']'
+ test 12x '!=' 0x
+ test -n 'Check lowntfs-3g -o atime failed.'
+ LOG_ERROR 'Check lowntfs-3g -o atime failed.'
+ message='Check lowntfs-3g -o atime failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check lowntfs-3g -o atime failed.'
Wed Dec  7 23:53:38 2022 - ERROR - Check lowntfs-3g -o atime failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 52'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 52'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 52'
Wed Dec  7 23:53:38 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 52
+ return 0
+ df -h
+ grep /dev/vdb
+ CHECK_RESULT 1 0 0 'Check disk mount failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check disk mount failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check disk mount failed.'
+ LOG_ERROR 'Check disk mount failed.'
+ message='Check disk mount failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check disk mount failed.'
Wed Dec  7 23:53:39 2022 - ERROR - Check disk mount failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 54'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 54'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 54'
Wed Dec  7 23:53:39 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 54
+ return 0
+ umount /mnt/windows
umount: /mnt/windows: not mounted.
+ lowntfs-3g /dev/vdb /mnt/windows -o noatime
NTFS signature is missing.
Failed to mount '/dev/vdb': Invalid argument
The device '/dev/vdb' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?
+ CHECK_RESULT 12 0 0 'Check lowntfs-3g -o noatime failed.'
+ actual_result=12
+ expect_result=0
+ mode=0
+ error_log='Check lowntfs-3g -o noatime failed.'
+ '[' -z 12 ']'
+ '[' 0 -eq 0 ']'
+ test 12x '!=' 0x
+ test -n 'Check lowntfs-3g -o noatime failed.'
+ LOG_ERROR 'Check lowntfs-3g -o noatime failed.'
+ message='Check lowntfs-3g -o noatime failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check lowntfs-3g -o noatime failed.'
Wed Dec  7 23:53:40 2022 - ERROR - Check lowntfs-3g -o noatime failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 57'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 57'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 57'
Wed Dec  7 23:53:40 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 57
+ return 0
+ df -h
+ grep /dev/vdb
+ CHECK_RESULT 1 0 0 'Check disk mount failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check disk mount failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check disk mount failed.'
+ LOG_ERROR 'Check disk mount failed.'
+ message='Check disk mount failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check disk mount failed.'
Wed Dec  7 23:53:41 2022 - ERROR - Check disk mount failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 59'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 59'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 59'
Wed Dec  7 23:53:42 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 59
+ return 0
+ umount /mnt/windows
umount: /mnt/windows: not mounted.
+ lowntfs-3g /dev/vdb /mnt/windows -o relatime
NTFS signature is missing.
Failed to mount '/dev/vdb': Invalid argument
The device '/dev/vdb' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?
+ CHECK_RESULT 12 0 0 'Check lowntfs-3g -o relatime failed.'
+ actual_result=12
+ expect_result=0
+ mode=0
+ error_log='Check lowntfs-3g -o relatime failed.'
+ '[' -z 12 ']'
+ '[' 0 -eq 0 ']'
+ test 12x '!=' 0x
+ test -n 'Check lowntfs-3g -o relatime failed.'
+ LOG_ERROR 'Check lowntfs-3g -o relatime failed.'
+ message='Check lowntfs-3g -o relatime failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check lowntfs-3g -o relatime failed.'
Wed Dec  7 23:53:42 2022 - ERROR - Check lowntfs-3g -o relatime failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 62'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 62'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 62'
Wed Dec  7 23:53:43 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 62
+ return 0
+ df -h
+ grep /dev/vdb
+ CHECK_RESULT 1 0 0 'Check disk mount failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check disk mount failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check disk mount failed.'
+ LOG_ERROR 'Check disk mount failed.'
+ message='Check disk mount failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check disk mount failed.'
Wed Dec  7 23:53:43 2022 - ERROR - Check disk mount failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 64'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 64'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 64'
Wed Dec  7 23:53:44 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 64
+ return 0
+ umount /mnt/windows
umount: /mnt/windows: not mounted.
+ lowntfs-3g /dev/vdb /mnt/windows -o delay_mtime
NTFS signature is missing.
Failed to mount '/dev/vdb': Invalid argument
The device '/dev/vdb' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?
+ CHECK_RESULT 12 0 0 'Check lowntfs-3g -o delay_mtime failed.'
+ actual_result=12
+ expect_result=0
+ mode=0
+ error_log='Check lowntfs-3g -o delay_mtime failed.'
+ '[' -z 12 ']'
+ '[' 0 -eq 0 ']'
+ test 12x '!=' 0x
+ test -n 'Check lowntfs-3g -o delay_mtime failed.'
+ LOG_ERROR 'Check lowntfs-3g -o delay_mtime failed.'
+ message='Check lowntfs-3g -o delay_mtime failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check lowntfs-3g -o delay_mtime failed.'
Wed Dec  7 23:53:44 2022 - ERROR - Check lowntfs-3g -o delay_mtime failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 67'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 67'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 67'
Wed Dec  7 23:53:45 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 67
+ return 0
+ df -h
+ grep /dev/vdb
+ CHECK_RESULT 1 0 0 'Check disk mount failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check disk mount failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check disk mount failed.'
+ LOG_ERROR 'Check disk mount failed.'
+ message='Check disk mount failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check disk mount failed.'
Wed Dec  7 23:53:46 2022 - ERROR - Check disk mount failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 69'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 69'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 69'
Wed Dec  7 23:53:46 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 69
+ return 0
+ umount /mnt/windows
umount: /mnt/windows: not mounted.
+ lowntfs-3g /dev/vdb /mnt/windows -o show_sys_files
NTFS signature is missing.
Failed to mount '/dev/vdb': Invalid argument
The device '/dev/vdb' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?
+ CHECK_RESULT 12 0 0 'Check lowntfs-3g -o show_sys_files failed.'
+ actual_result=12
+ expect_result=0
+ mode=0
+ error_log='Check lowntfs-3g -o show_sys_files failed.'
+ '[' -z 12 ']'
+ '[' 0 -eq 0 ']'
+ test 12x '!=' 0x
+ test -n 'Check lowntfs-3g -o show_sys_files failed.'
+ LOG_ERROR 'Check lowntfs-3g -o show_sys_files failed.'
+ message='Check lowntfs-3g -o show_sys_files failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check lowntfs-3g -o show_sys_files failed.'
Wed Dec  7 23:53:47 2022 - ERROR - Check lowntfs-3g -o show_sys_files failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 72'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 72'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 72'
Wed Dec  7 23:53:47 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 72
+ return 0
+ df -h
+ grep /dev/vdb
+ CHECK_RESULT 1 0 0 'Check disk mount failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check disk mount failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check disk mount failed.'
+ LOG_ERROR 'Check disk mount failed.'
+ message='Check disk mount failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check disk mount failed.'
Wed Dec  7 23:53:48 2022 - ERROR - Check disk mount failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 74'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 74'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 74'
Wed Dec  7 23:53:49 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 74
+ return 0
+ umount /mnt/windows
umount: /mnt/windows: not mounted.
+ lowntfs-3g /dev/vdb /mnt/windows -o hide_hid_files
NTFS signature is missing.
Failed to mount '/dev/vdb': Invalid argument
The device '/dev/vdb' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?
+ CHECK_RESULT 12 0 0 'Check lowntfs-3g -o hide_hid_files failed.'
+ actual_result=12
+ expect_result=0
+ mode=0
+ error_log='Check lowntfs-3g -o hide_hid_files failed.'
+ '[' -z 12 ']'
+ '[' 0 -eq 0 ']'
+ test 12x '!=' 0x
+ test -n 'Check lowntfs-3g -o hide_hid_files failed.'
+ LOG_ERROR 'Check lowntfs-3g -o hide_hid_files failed.'
+ message='Check lowntfs-3g -o hide_hid_files failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check lowntfs-3g -o hide_hid_files failed.'
Wed Dec  7 23:53:49 2022 - ERROR - Check lowntfs-3g -o hide_hid_files failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 77'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 77'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 77'
Wed Dec  7 23:53:50 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 77
+ return 0
+ df -h
+ grep /dev/vdb
+ CHECK_RESULT 1 0 0 'Check disk mount failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Check disk mount failed.'
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Check disk mount failed.'
+ LOG_ERROR 'Check disk mount failed.'
+ message='Check disk mount failed.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'Check disk mount failed.'
Wed Dec  7 23:53:50 2022 - ERROR - Check disk mount failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 79'
+ message='oe_test_ntfs-3g_lowntfs-3g_02.sh line 79'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'oe_test_ntfs-3g_lowntfs-3g_02.sh line 79'
Wed Dec  7 23:53:51 2022 - ERROR - oe_test_ntfs-3g_lowntfs-3g_02.sh line 79
+ return 0
+ umount /mnt/windows
umount: /mnt/windows: not mounted.
+ LOG_INFO 'End of the test.'
+ message='End of the test.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'End of the test.'
Wed Dec  7 23:53:51 2022 - INFO  - End of the test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 20
+ test 20 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Dec  7 23:53:52 2022 - ERROR - failed to execute the case.
+ exit 20
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed Dec  7 23:53:53 2022 - INFO  - Start to restore the test environment.
+ expect
spawn mkfs.ext4 /dev/vdb
y
mke2fs 1.46.5 (30-Dec-2021)
/dev/vdb contains a ext4 file system
	created on Wed Dec  7 23:52:37 2022
Proceed anyway? (y,N) Discarding device blocks:      0/512000             done                            
Creating filesystem with 512000 1k blocks and 128016 inodes
Filesystem UUID: a8bbd8cd-c39f-44b3-bffd-7d32bb2e62a4
Superblock backups stored on blocks: 
	8193, 24577, 40961, 57345, 73729, 204801, 221185, 401409

Allocating group tables:  0/63     done                            
Writing inode tables:  0/63     done                            
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information:  0/63     done

+ rm -rf /mnt/windows
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpdyxhztjz ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen-riscv/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpdyxhztjz
+ '[' 0 -ne 0 ']'
+ LOG_INFO 'Finish restoring the test environment.'
+ message='Finish restoring the test environment.'
+ python3 /root/mugen-riscv/libs/locallibs/mugen_log.py --level info --message 'Finish restoring the test environment.'
Wed Dec  7 23:54:03 2022 - INFO  - Finish restoring the test environment.
